###
# EDIT THIS PAGE BUT DO NOT REMOVE THE OBJECTS
###

# the order of the slides, using the names of the files
# NOTE - slide filenames MUST BE VALID PYTHON VARIABLE NAMES
slide_order = [
        "intro",
        "overview0",
        "overview1",
        "overview2",
        "overview3",
        "overview4",
        "overview5",
        "importantDefs0",
        "importantDefs1",
        "importantDefs2",
        "dataGeneratorApplication0",
        "dataGeneratorApplication01",
        "dataGeneratorApplication02",
        "dataGeneratorApplication1",
        "executionEnvironment0",
        "executionEnvironment1",
        # "configurableParameters0",
        # "configurableParameters1",
        # "configurableParameters2",
        # "configurableParameters3",
        # "configurableParameters4",
        "featuresInPractice2",
        "featuresInPractice3",
        "featuresInPractice0",
        "featuresInPractice1",
        # "preliminaryExperiments",
        "statisticalAnalysis",
        "statisticalAnalysisDistribution",
        "statisticalAnalysisMultipleDist",
        "messageScalesAnalysis",
        "constantMessageSizes",
        "commCompInterference0",
        "commCompInterference1",
        "commCompInterference2",
        "commCompInterference3",
        "memoryBoundInterference",
        "computeBoundInterference",
        "commCompInterferenceComp32",
        "insightsGainedExp",
        # "modelTypes0",
        # "modelTypes1",
        # "modelTypes2",
        "modelTypes3",
        "semiEmpiricalModel",
        "semiEmpiricalModel2",
        # "mlConcepts0",
        # "mlConcepts1",
        # "mlConcepts2",
        "mlConcepts3",
        # "mlConcepts4",
        "rfAndGB",
        "dataFiltering",
        # "modelScenarios",
        "messageSizeModel",
        "trainSmallTestBig",
        "mainModel",
        "btPrediction0",
        "btPrediction1", "final"

]
slide_orderDict = {
        "intro"                          : "Introduction",
        "overview0"                      : "Overview 0",
        "overview1"                      : "Overview 1",
        "overview2"                      : "Overview 2",
        "overview3"                      : "Overview 3",
        "overview4"                      : "Overview 4",
        "overview5"                      : "Overview 5",
        "importantDefs0"                 : "Important Definitions",
        "importantDefs1"                 : "Important Definitions",
        "importantDefs2"                 : "Important Definitions",
        "dataGeneratorApplication0"      : "Data Generator Application",
        "dataGeneratorApplication1"      : "Data Generator Application",
        "executionEnvironment0"          : "Execution Environment",
        "executionEnvironment1"          : "Execution Environment",
        # "configurableParameters0"        : "Configurable Parameters",
        # "configurableParameters1"        : "Configurable Parameters",
        # "configurableParameters2"        : "Configurable Parameters",
        # "configurableParameters3"        : "Configurable Parameters",
        # "configurableParameters4"        : "Configurable Parameters",
        "featuresInPractice0"            : "Feature Review",
        "featuresInPractice1"            : "Feature Review",
        "featuresInPractice2"            : "Feature Review",
        "featuresInPractice3"            : "Feature Review",
        # "preliminaryExperiments"         : "Preliminary Experiments",
        "statisticalAnalysis"            : "Statistical Analysis 1",
        "statisticalAnalysisDistribution": "Statistical Analysis 2",
        "statisticalAnalysisMultipleDist": "Statistical Analysis 3",
        "messageScalesAnalysis"          : "Message Size Scale Analysis",
        "constantMessageSizes"           : "Constant Message Sizes Scenario",
        "commCompInterference0"          : "Communication-Computation Interference 1",
        "commCompInterference1"          : "Communication-Computation Interference 1",
        "commCompInterference2"          : "Communication-Computation Interference 1",
        "commCompInterference3"          : "Communication-Computation Interference 1",
        "memoryBoundInterference"        : "Communication-Computation Interference 2",
        "computeBoundInterference"       : "Communication-Computation Interference 3",
        "commCompInterferenceComp32"     : "Communication-Computation Interference 4",
        "insightsGainedExp"              : "Insights Gained",
        # "modelTypes0"                    : "Basic Modeling Concepts",
        # "modelTypes1"                    : "Basic Modeling Concepts",
        # "modelTypes2"                    : "Basic Modeling Concepts",
        "modelTypes3"                    : "Basic Modeling Concepts",
        "semiEmpiricalModel"             : "Semi-Empirical Model 1",
        "semiEmpiricalModel2"            : "Semi-Empirical Model 2",
        # "mlConcepts0"                    : "Machine Learning Concepts",
        # "mlConcepts1"                    : "Machine Learning Concepts",
        # "mlConcepts2"                    : "Machine Learning Concepts",
        "mlConcepts3"                    : "Machine Learning Concepts",
        # "mlConcepts4"                    : "Machine Learning Concepts",
        "rfAndGB"                        : "Random Forests and Gradient Boosting",
        "dataFiltering"                  : 'Data Gathering and Filtering',
        # "modelScenarios"                 : "Model Scenarios",
        "messageSizeModel"               : "Message Size Models",
        "trainSmallTestBig"              : "Train Small/Test Big Model",
        "mainModel"                      : "Main Model",
        "btPrediction0"                  : "NAS BT Prediction",
        "btPrediction1"                  : "NAS BT Prediction",
        "final"                          : "final"

}
# the text that appears in the tab
presentation_title = "F.B. Diploma Thesis"

# the text that appears in the previous and next buttons
prev_text = "<"
next_text = ">"
